INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (1, 'Bob', 'Stone', 'Stone@mail.com','Accountant', 6)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (2, 'Suzzi', 'Stone', 'Suzzi@Stone.net', 'Receptionist', 2)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (3, 'Hannah', 'Smith', 'Smith1990@mail.com', 'Youth Worker', 4)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (4, 'Bert', 'McDonal', 'McDonal@gmail.com', 'Media', 4)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (5, 'John', 'Smith', 'John.Smith@live.co.uk', 'Manager', 5)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (6, 'Jane', 'Doe', 'Doeyedjane@hotmail.com', 'Customer Care', 3)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (7, 'Bob', 'Zane', 'zaney@yahoo.com', 'Creative Lead', 4)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (8, 'Sam', 'McDan', 'Sam-McDan@gmail.com', 'Media', 3)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (9, 'Joe', 'Rich', 'WhoAmI123@hotmail.com', 'IT', 2)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (10, 'Felix', 'King', 'TheKing@mail.com', 'Trainee', 1)
INSERT INTO CHECKIN (logID, timeIn, timeOut, hours, staffID) VALUES (1, '09:00', '17:00', 8.0, 1)
INSERT INTO CHECKIN (logID, timeIn, timeOut, hours, staffID) VALUES (2, '08:50', '17:20', 8.5, 2)
INSERT INTO CHECKIN (logID, timeIn, timeOut, hours, staffID) VALUES (3, '08:30', '16:00', 8.0, 3)
INSERT INTO CHECKIN (logID, timeIn, staffID) VALUES (4, '08:50', 1)
INSERT INTO CHECKIN (logID, timeIn, staffID) VALUES (5, '08:52', 3)
INSERT INTO CHECKIN (logID, timeIn, staffID) VALUES (6, '08:53', 7)
INSERT INTO CHECKIN (logID, timeIn, staffID) VALUES (7, '08:53', 2)
INSERT INTO CHECKIN (logID, timeIn, staffID) VALUES (8, '08:54', 9)
INSERT INTO CHECKIN (logID, timeIn, staffID) VALUES (9, '08:55', 10)
INSERT INTO CHECKIN (logID, timeIn, staffID) VALUES (10, '08:56', 8)