INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (1, 'Bob', 'Stone', 'Stone@mail.com','Accountant', 6)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (2, 'Suzzi', 'Stone', 'Suzzi@Stone.net', 'Receptionist', 2)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (3, 'Hannah', 'Smith', 'Smith1990@mail.com', 'Youth Worker', 4)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (4, 'Bert', 'McDonal', 'McDonal@gmail.com', 'Media', 4)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (5, 'John', 'Smith', 'John.Smith@live.co.uk', 'Manager', 5)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (6, 'Jane', 'Doe', 'Doeyedjane@hotmail.com', 'Customer Care', 3)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (7, 'Bob', 'Zane', 'zaney@yahoo.com', 'Creative Lead', 4)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (8, 'Sam', 'McDan', 'Sam-McDan@gmail.com', 'Media', 3)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (9, 'Joe', 'Rich', 'WhoAmI123@hotmail.com', 'IT', 2)
INSERT INTO STAFF (staffID, firstName, lastName, email, jobRole, payTier) VALUES (10, 'Felix', 'King', 'TheKing@mail.com', 'Trainee', 1)
INSERT INTO CHECKIN (logID, timeIn, timeOut, hours, staffID) VALUES (1, '2019/6/19 09:00:32', '2019/6/19 17:00:32', 8.0, 1)
INSERT INTO CHECKIN (logID, timeIn, timeOut, hours, staffID) VALUES (2, '2019/6/19 08:50:32', '2019/6/19 17:20:32', 8.5, 2)
INSERT INTO CHECKIN (logID, timeIn, timeOut, hours, staffID) VALUES (3, '2019/6/19 08:30:32', '2019/6/19 16:00:32', 8.0, 3)
INSERT INTO CHECKIN (logID, timeIn, hours, staffID) VALUES (4, '2019/6/19 08:50:32', 0.0, 1)
INSERT INTO CHECKIN (logID, timeIn, hours, staffID) VALUES (5, '2019/6/19 08:52:32', 0.0, 3)
INSERT INTO CHECKIN (logID, timeIn, hours, staffID) VALUES (6, '2019/6/19 08:53:32', 0.0, 7)
INSERT INTO CHECKIN (logID, timeIn, hours, staffID) VALUES (7, '2019/6/19 08:53:54', 0.0, 2)
INSERT INTO CHECKIN (logID, timeIn, hours, staffID) VALUES (8, '2019/6/19 08:54:32', 0.0, 9)
INSERT INTO CHECKIN (logID, timeIn, hours, staffID) VALUES (9, '2019/6/19 08:55:32', 0.0, 10)
INSERT INTO CHECKIN (logID, timeIn, hours, staffID) VALUES (10, '2019/6/19 08:56:32', 0.0, 8)